/* eslint-disable @next/next/no-img-element */
"use client";

import { useMemo, useState, type ChangeEvent } from "react";

type Role = "employee" | "leader" | "manager" | "admin";
type View = "dashboard" | "applications" | "application" | "new-application" | "employees" | "partners" | "users" | "marketing" | "client-consent" | "login" | "otp";
type Application = { id: string; crm: string; client: string; phone: string; property: string; amount: string; created: string; status: string; owner: string; updated: string };

const initialApplications: Application[] = [
  { id: "CI-240814-0187", crm: "84517392", client: "Анна Викторовна Орлова", phone: "+7 928 555-28-14", property: "ЖК «Левенцовка Парк», кв. 184", amount: "6 800 000 ₽", created: "14.08.2026", status: "Предварительно одобрена", owner: "Елена Кравцова", updated: "Сегодня, 09:42" },
  { id: "CI-240814-0185", crm: "84517281", client: "Максим Олегович Савельев", phone: "+7 918 201-65-80", property: "ЖК «Северный Берег», кв. 72", amount: "5 200 000 ₽", created: "14.08.2026", status: "Ожидает согласия клиента", owner: "Илья Романов", updated: "Сегодня, 09:18" },
  { id: "CI-230814-0179", crm: "84516044", client: "Дарья Игоревна Нечаева", phone: "+7 988 745-09-12", property: "ЖК «Грин Парк», кв. 308", amount: "8 150 000 ₽", created: "13.08.2026", status: "На проверке", owner: "Елена Кравцова", updated: "Вчера, 17:30" },
  { id: "CI-220814-0168", crm: "84514911", client: "Алексей Сергеевич Жуков", phone: "+7 960 449-37-11", property: "ЖК «Сокол», кв. 91", amount: "4 900 000 ₽", created: "12.08.2026", status: "Одобрена", owner: "Илья Романов", updated: "12.08, 16:05" },
  { id: "CI-210814-0159", crm: "84513278", client: "Мария Павловна Котова", phone: "+7 928 322-71-65", property: "ЖК «Грин Парк», кв. 112", amount: "7 300 000 ₽", created: "11.08.2026", status: "Отклонена", owner: "Елена Кравцова", updated: "11.08, 14:51" },
  { id: "CI-190814-0141", crm: "84511002", client: "Николай Андреевич Панов", phone: "+7 951 820-43-17", property: "ЖК «Левенцовка Парк», кв. 36", amount: "6 050 000 ₽", created: "09.08.2026", status: "Исполнена", owner: "Илья Романов", updated: "09.08, 12:20" },
];

const statusOrder = ["Черновик", "Ожидает согласия клиента", "На проверке", "Предварительно одобрена", "Одобрена", "Отклонена", "Исполнена"];
const roleLabels: Record<Role, string> = { employee: "Сотрудник партнёра", leader: "Руководитель партнёра", manager: "Менеджер банка", admin: "Администратор банка" };
const navByRole: Record<Role, { view: View; label: string; icon: string }[]> = {
  employee: [{ view: "dashboard", label: "Главная", icon: "home" }, { view: "applications", label: "Заявки", icon: "file" }, { view: "new-application", label: "Новая заявка", icon: "plus" }],
  leader: [{ view: "dashboard", label: "Главная", icon: "home" }, { view: "applications", label: "Заявки", icon: "file" }, { view: "new-application", label: "Новая заявка", icon: "plus" }, { view: "employees", label: "Сотрудники", icon: "users" }],
  manager: [{ view: "dashboard", label: "Рабочий стол", icon: "home" }, { view: "applications", label: "Заявки партнёров", icon: "file" }],
  admin: [{ view: "dashboard", label: "Обзор", icon: "home" }, { view: "partners", label: "Партнёры", icon: "building" }, { view: "users", label: "Пользователи", icon: "users" }, { view: "marketing", label: "Баннеры", icon: "image" }],
};

function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    home: <><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5M9 21v-7h6v7"/></>, file: <><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></>, plus: <><path d="M12 5v14M5 12h14"/></>,
    users: <><circle cx="9" cy="8" r="3"/><path d="M3 20c.4-4 2.3-6 6-6s5.6 2 6 6"/><circle cx="17" cy="9" r="2"/><path d="M16 15c3.2 0 4.7 1.7 5 5"/></>, building: <><path d="M4 22V4h11v18M15 9h5v13M8 8h3M8 12h3M8 16h3M18 13v2M18 18v2M2 22h20"/></>, image: <><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m5 18 5-5 3 3 2-2 4 4"/></>,
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>, search: <><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>, chevron: <path d="m9 18 6-6-6-6"/>, download: <><path d="M12 3v12M7 10l5 5 5-5"/><path d="M4 20h16"/></>, upload: <><path d="M12 16V4M7 9l5-5 5 5"/><path d="M4 20h16"/></>, copy: <><rect x="8" y="8" width="11" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h2"/></>,
    phone: <path d="M6 3h4l1 5-2.5 1.5a15 15 0 0 0 6 6L16 13l5 1v4c0 1.7-1.3 3-3 3A15 15 0 0 1 3 6c0-1.7 1.3-3 3-3Z"/>, mail: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>, check: <path d="m5 12 4 4L19 6"/>, close: <path d="m6 6 12 12M18 6 6 18"/>, menu: <path d="M4 7h16M4 12h16M4 17h16"/>, logout: <><path d="M10 4H5v16h5M14 8l4 4-4 4M9 12h9"/></>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] ?? paths.file}</svg>;
}

function StatusBadge({ status }: { status: string }) {
  const className = status.toLowerCase().replaceAll(" ", "-").replaceAll("ё", "е");
  return <span className={`status status--${className}`}>{status}</span>;
}
function Field({ label, value, type = "text", placeholder }: { label: string; value?: string; type?: string; placeholder?: string }) {
  return <label className="field"><span>{label}</span><input type={type} defaultValue={value} placeholder={placeholder}/></label>;
}

export default function Home() {
  const [role, setRole] = useState<Role>("leader");
  const [view, setView] = useState<View>("dashboard");
  const [applications, setApplications] = useState(initialApplications);
  const [selectedId, setSelectedId] = useState(initialApplications[0].id);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("Все статусы");
  const [detailTab, setDetailTab] = useState("overview");
  const [wizardStep, setWizardStep] = useState(0);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [modal, setModal] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [otp, setOtp] = useState("");
  const [consents, setConsents] = useState([false, false, false]);
  const [esiaDone, setEsiaDone] = useState(false);
  const [docs, setDocs] = useState([
    { name: "Паспорт_Орлова.pdf", size: "2,4 МБ", author: "Елена Кравцова", source: "Партнёр", date: "14.08.2026, 09:24" },
    { name: "Справка_о_доходах.pdf", size: "1,1 МБ", author: "Елена Кравцова", source: "Партнёр", date: "14.08.2026, 09:25" },
    { name: "Предварительное_решение.pdf", size: "468 КБ", author: "Андрей Лебедев", source: "Банк", date: "14.08.2026, 09:42" },
  ]);
  const currentApplication = applications.find((app) => app.id === selectedId) ?? applications[0];
  const filteredApplications = useMemo(() => applications.filter((app) => [app.id, app.crm, app.client, app.property].join(" ").toLowerCase().includes(search.toLowerCase()) && (statusFilter === "Все статусы" || app.status === statusFilter)), [applications, search, statusFilter]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(null), 2600); };
  const openApplication = (id: string) => { setSelectedId(id); setDetailTab("overview"); setView("application"); setMobileMenu(false); };
  const selectRole = (nextRole: Role) => { setRole(nextRole); setView("dashboard"); setMobileMenu(false); notify(`Режим: ${roleLabels[nextRole]}`); };
  const uploadDocument = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setDocs((items) => [...items, { name: file.name, size: file.size ? `${Math.max(1, Math.round(file.size / 1024))} КБ` : "1,2 МБ", author: role === "manager" ? "Андрей Лебедев" : "Елена Кравцова", source: role === "manager" ? "Банк" : "Партнёр", date: "Сегодня, 10:12" }]); notify("Документ добавлен в заявку"); };
  const submitApplication = () => { const item: Application = { id: "CI-240814-0191", crm: "№ формируется", client: "Софья Андреевна Волкова", phone: "+7 928 440-18-62", property: "ЖК «Грин Парк», кв. 214", amount: "7 450 000 ₽", created: "14.08.2026", status: "Ожидает согласия клиента", owner: "Елена Кравцова", updated: "Только что" }; setApplications((items) => [item, ...items]); setSelectedId(item.id); setWizardStep(0); setDetailTab("overview"); setView("application"); notify("Заявка отправлена. Код на сайте присвоен"); };

  if (view === "login" || view === "otp") return <AuthView view={view} setView={setView} otp={otp} setOtp={setOtp} notify={notify} toast={toast}/>;
  if (view === "client-consent") return <ClientConsent application={currentApplication} consents={consents} setConsents={setConsents} esiaDone={esiaDone} setEsiaDone={setEsiaDone} setView={setView}/>;

  const pageTitle: Record<string, string> = { dashboard: role === "admin" ? "Обзор системы" : role === "manager" ? "Рабочий стол" : "Добрый день, Елена!", applications: role === "manager" ? "Заявки партнёров" : "Заявки", employees: "Сотрудники", partners: "Партнёры", users: "Пользователи", marketing: "Рекламные баннеры" };
  const renderView = () => {
    if (view === "dashboard") return <Dashboard role={role} applications={applications} setView={setView} setStatusFilter={setStatusFilter} openApplication={openApplication} notify={notify}/>;
    if (view === "applications") return <Applications applications={applications} filtered={filteredApplications} search={search} setSearch={setSearch} statusFilter={statusFilter} setStatusFilter={setStatusFilter} openApplication={openApplication}/>;
    if (view === "application") return <ApplicationDetail application={currentApplication} detailTab={detailTab} setDetailTab={setDetailTab} setView={setView} role={role} docs={docs} uploadDocument={uploadDocument} notify={notify} setModal={setModal}/>;
    if (view === "new-application") return <NewApplication wizardStep={wizardStep} setWizardStep={setWizardStep} notify={notify} submitApplication={submitApplication}/>;
    if (view === "employees") return <Employees setModal={setModal}/>;
    if (view === "partners") return <Partners setModal={setModal}/>;
    if (view === "users") return <Users setModal={setModal} notify={notify}/>;
    if (view === "marketing") return <Marketing notify={notify}/>;
    return null;
  };

  return <main className="app-shell">
    <aside className={`sidebar ${mobileMenu ? "sidebar--open" : ""}`}>
      <div className="sidebar__logo"><img src="/centrinvest-logo.svg" alt="Банк Центр-инвест"/><span>Кабинет партнёра</span></div>
      <div className="partner-identity"><span className="partner-identity__mark">{role === "admin" || role === "manager" ? "ЦИ" : "ГП"}</span><div><strong>{role === "admin" || role === "manager" ? "Банк «Центр-инвест»" : "ООО СЗ «Грин Парк»"}</strong><small>{roleLabels[role]}</small></div></div>
      <nav>{navByRole[role].map((item) => <button key={item.view} className={view === item.view ? "active" : ""} onClick={() => { setView(item.view); setMobileMenu(false); }}><Icon name={item.icon}/><span>{item.label}</span>{item.view === "applications" && <em>{applications.length}</em>}</button>)}</nav>
      <div className="sidebar__support"><span>Нужна помощь?</span><strong>8 800 200-99-29</strong><small>Бесплатно по России</small></div>
      <button className="sidebar__logout" onClick={() => setView("login")}><Icon name="logout" size={19}/>Выйти</button>
    </aside>
    {mobileMenu && <button className="mobile-overlay" onClick={() => setMobileMenu(false)} aria-label="Закрыть меню"/>}
    <section className="workspace">
      <header className="topbar">
        <button className="mobile-menu-button" onClick={() => setMobileMenu(true)} aria-label="Открыть меню"><Icon name="menu"/></button>
        <div className="role-switcher"><span>Роль в прототипе</span><select value={role} onChange={(e) => selectRole(e.target.value as Role)}><option value="employee">Сотрудник партнёра</option><option value="leader">Руководитель партнёра</option><option value="manager">Менеджер банка</option><option value="admin">Администратор банка</option></select></div>
        <div className="topbar__actions"><button className="icon-button notification-button" onClick={() => setNotificationsOpen(!notificationsOpen)} aria-label="Уведомления"><Icon name="bell"/><em>3</em></button><div className="user-avatar">{role === "admin" ? "ОР" : role === "manager" ? "АЛ" : "ЕК"}</div><div className="topbar-user"><strong>{role === "admin" ? "Ольга Руденко" : role === "manager" ? "Андрей Лебедев" : "Елена Кравцова"}</strong><small>{roleLabels[role]}</small></div></div>
        {notificationsOpen && <div className="notifications-popover"><div><h3>Уведомления</h3><button className="link-button" onClick={() => notify("Все уведомления прочитаны")}>Прочитать все</button></div>{[["Статус заявки изменён", "CI-240814-0187 · Предварительно одобрена", "5 минут назад"], ["Получены согласия клиента", "CI-230814-0179 · Заявка принята в работу", "32 минуты назад"], ["Новый документ от банка", "Предварительное решение.pdf", "Сегодня, 09:42"]].map((item) => <button key={item[0]} onClick={() => { setNotificationsOpen(false); openApplication(initialApplications[0].id); }}><span className="notification-dot"/><div><strong>{item[0]}</strong><p>{item[1]}</p><small>{item[2]}</small></div></button>)}</div>}
      </header>
      <div className="workspace__content">
        {view !== "application" && view !== "new-application" && <div className="page-heading"><div><span className="eyebrow">{role === "admin" ? "Администрирование" : role === "manager" ? "Банк «Центр-инвест»" : "ООО СЗ «Грин Парк»"}</span><h1>{pageTitle[view] ?? "Личный кабинет"}</h1>{view === "dashboard" && role !== "admin" && <p>{role === "manager" ? "Заявки, требующие вашего внимания." : "Сводка по ипотечным заявкам вашей организации."}</p>}</div>{view === "dashboard" && (role === "employee" || role === "leader") && <button className="button button--primary" onClick={() => setView("new-application")}><Icon name="plus" size={18}/>Новая заявка</button>}</div>}
        {view === "new-application" && <div className="page-heading page-heading--wizard"><div><button className="back-link" onClick={() => setView("applications")}>← К заявкам</button><h1>Новая ипотечная заявка</h1><p>Черновик сохраняется автоматически</p></div></div>}
        {renderView()}
      </div>
    </section>
    <Modal modal={modal} setModal={setModal} setDocs={setDocs} notify={notify}/>
    {toast && <div className="toast"><Icon name="check" size={18}/>{toast}</div>}
  </main>;
}

function AuthView({ view, setView, otp, setOtp, notify, toast }: { view: View; setView: (v: View) => void; otp: string; setOtp: (v: string) => void; notify: (m: string) => void; toast: string | null }) {
  return <main className="auth-page"><section className="auth-brand"><img src="/centrinvest-logo.svg" alt="Банк Центр-инвест" className="auth-logo"/><div className="auth-brand__content"><span className="eyebrow eyebrow--light">Личный кабинет партнёра</span><h1>Ипотечные заявки — в одном рабочем пространстве</h1><p>Передавайте заявки, отслеживайте решения банка и обменивайтесь документами онлайн.</p></div><div className="auth-orbits" aria-hidden="true"><i/><i/><i/></div></section><section className="auth-form-wrap"><div className="auth-form"><span className="prototype-label">Демонстрационный режим</span>{view === "login" ? <><h2>Вход в кабинет</h2><p className="muted">Используйте учётную запись, созданную администратором банка.</p><Field label="Электронная почта" value="e.kravtsova@greenpark.ru" type="email"/><Field label="Пароль" value="Partner2026!" type="password"/><button className="link-button auth-forgot" onClick={() => notify("Инструкция отправлена на email")}>Забыли пароль?</button><button className="button button--primary button--wide" onClick={() => setView("otp")}>Продолжить</button><p className="auth-hint">Для просмотра прототипа можно использовать заполненные данные.</p></> : <><button className="back-link" onClick={() => setView("login")}>← Назад</button><h2>Подтвердите вход</h2><p className="muted">Код отправлен на номер <strong>+7 ••• •••-42-18</strong></p><label className="field otp-field"><span>Код из SMS</span><input autoFocus value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="000000"/></label><div className="otp-digits">{[0,1,2,3,4,5].map((i) => <span key={i} className={otp.length > i ? "filled" : ""}/>)}</div><button className="button button--primary button--wide" onClick={() => { setView("dashboard"); setOtp(""); notify("Вход выполнен"); }}>Войти</button><button className="link-button auth-resend" onClick={() => notify("Новый код отправлен")}>Отправить код повторно</button></>}</div></section>{toast && <div className="toast"><Icon name="check" size={18}/>{toast}</div>}</main>;
}

function ClientConsent({ application, consents, setConsents, esiaDone, setEsiaDone, setView }: { application: Application; consents: boolean[]; setConsents: React.Dispatch<React.SetStateAction<boolean[]>>; esiaDone: boolean; setEsiaDone: (v: boolean) => void; setView: (v: View) => void }) {
  const allChecked = consents.every(Boolean);
  return <main className="client-page"><header className="client-header"><img src="/centrinvest-logo.svg" alt="Банк Центр-инвест"/><span>Защищённая страница</span></header><div className="client-container"><div className="client-progress"><span className={esiaDone ? "done" : "active"}>1</span><i/><span className={esiaDone ? "active" : ""}>2</span><i/><span className={allChecked ? "active" : ""}>3</span></div>{!esiaDone ? <section className="client-card client-card--center"><div className="esia-mark">Г</div><span className="eyebrow">Подтверждение личности</span><h1>Авторизуйтесь через Госуслуги</h1><p>Это необходимо, чтобы подтвердить вашу личность и оформить согласия по заявке <strong>{application.id}</strong>.</p><div className="security-note"><Icon name="check"/><span>Банк не получает пароль от вашей учётной записи Госуслуг.</span></div><button className="button button--primary" onClick={() => setEsiaDone(true)}>Войти через Госуслуги</button><button className="link-button" onClick={() => setView("application")}>Вернуться в демонстрацию ЛКП</button></section> : allChecked ? <section className="client-card client-card--center success-card"><div className="success-icon"><Icon name="check" size={34}/></div><span className="eyebrow">Готово</span><h1>Согласия предоставлены</h1><p>Заявка принята банком в работу. Партнёр увидит обновлённый статус в личном кабинете.</p><div className="success-reference"><span>Код на сайте</span><strong>{application.id}</strong></div><button className="button button--secondary" onClick={() => { setEsiaDone(false); setConsents([false, false, false]); setView("application"); }}>Вернуться в прототип</button></section> : <section className="client-card"><span className="eyebrow">Шаг 2 из 3</span><h1>Согласия по кредитной заявке</h1><p className="muted">Ознакомьтесь с документами. Каждое согласие подтверждается отдельно.</p><div className="consent-list">{["Обработка персональных данных", "Запрос кредитной истории в БКИ", "Передача информации третьим лицам"].map((label, index) => <label className="consent-item" key={label}><input type="checkbox" checked={consents[index]} onChange={() => setConsents((values) => values.map((item, i) => i === index ? !item : item))}/><span className="custom-check"><Icon name="check" size={16}/></span><span><strong>{label}</strong><small>Открыть и прочитать полный текст согласия</small></span><Icon name="chevron" size={18}/></label>)}</div><div className="client-actions"><button className="button button--secondary" onClick={() => setEsiaDone(false)}>Назад</button><button className="button button--primary" disabled={!allChecked}>Подтвердить согласия</button></div></section>}</div></main>;
}

function Dashboard({ role, applications, setView, setStatusFilter, openApplication, notify }: { role: Role; applications: Application[]; setView: (v: View) => void; setStatusFilter: (v: string) => void; openApplication: (id: string) => void; notify: (m: string) => void }) {
  if (role === "admin") return <><div className="summary-grid summary-grid--admin">{[{label:"Активные партнёры",value:"24",delta:"+3 за месяц"},{label:"Пользователи",value:"186",delta:"174 активны"},{label:"Заявки сегодня",value:"38",delta:"из 11 организаций"},{label:"Заблокированы",value:"2",delta:"требуют внимания"}].map((item) => <article className="summary-card" key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.delta}</small></article>)}</div><div className="content-grid content-grid--wide"><section className="panel"><div className="panel__head"><div><span className="eyebrow">Контроль доступа</span><h2>Последние действия</h2></div><button className="link-button">Журнал действий</button></div><div className="activity-list">{[["Создан партнёр","ООО СЗ «Новый квартал»","5 минут назад"],["Разблокирован пользователь","И. В. Ларионов","32 минуты назад"],["Изменена роль","М. П. Краснова · Руководитель","Сегодня, 08:48"],["Обновлён баннер","Семейная ипотека","Вчера, 17:12"]].map((item) => <div className="activity-row" key={item[0]}><span className="activity-dot"/><div><strong>{item[0]}</strong><small>{item[1]}</small></div><time>{item[2]}</time></div>)}</div></section><section className="panel admin-attention"><span className="eyebrow">Требуют внимания</span><h2>2 заблокированных входа</h2><p>Пользователи превысили пять попыток входа.</p><button className="button button--secondary" onClick={() => setView("users")}>Перейти к пользователям</button></section></div></>;
  const counts = [{ label: "Всего заявок", value: applications.length, color: "green", filter: "Все статусы" }, { label: "Ожидают согласия", value: applications.filter((a) => a.status === "Ожидает согласия клиента").length, color: "yellow", filter: "Ожидает согласия клиента" }, { label: "На рассмотрении", value: applications.filter((a) => a.status === "На проверке").length, color: "blue", filter: "На проверке" }, { label: "Одобрены", value: applications.filter((a) => ["Предварительно одобрена", "Одобрена"].includes(a.status)).length, color: "mint", filter: "Одобрена" }];
  return <><div className="summary-grid">{counts.map((item) => <button className={`summary-card summary-card--${item.color}`} key={item.label} onClick={() => { setStatusFilter(item.filter); setView("applications"); }}><span>{item.label}</span><strong>{item.value}</strong><small>Перейти к списку <Icon name="chevron" size={14}/></small></button>)}</div><div className="content-grid"><section className="panel panel--applications"><div className="panel__head"><div><span className="eyebrow">Актуальное</span><h2>{role === "manager" ? "Заявки в работе" : "Последние заявки"}</h2></div><button className="link-button" onClick={() => setView("applications")}>Все заявки</button></div><div className="compact-apps">{applications.slice(0, 4).map((app) => <button className="compact-app" key={app.id} onClick={() => openApplication(app.id)}><span className="client-avatar">{app.client.split(" ").slice(0, 2).map((word) => word[0]).join("")}</span><span className="compact-app__main"><strong>{app.client}</strong><small>{app.id} · {app.amount}</small></span><StatusBadge status={app.status}/><span className="compact-app__time">{app.updated}</span><Icon name="chevron" size={18}/></button>)}</div></section><aside className="dashboard-side"><section className="promo-card"><span className="promo-card__tag">Для партнёров</span><h2>Семейная ипотека</h2><p>Расскажите клиентам о программе с господдержкой.</p><button onClick={() => notify("Материалы открыты")}>Материалы для продаж <Icon name="chevron" size={16}/></button><div className="promo-shape" aria-hidden="true"/></section><section className="manager-card"><div className="manager-card__head"><span className="manager-photo">АЛ</span><div><small>Ваш менеджер</small><strong>Андрей Лебедев</strong></div><span className="online-dot"/></div><div className="manager-links"><a href="tel:+78632001212"><Icon name="phone" size={17}/>+7 863 200-12-12</a><a href="mailto:a.lebedev@centrinvest.ru"><Icon name="mail" size={17}/>Написать письмо</a></div></section></aside></div></>;
}

function Applications({ applications, filtered, search, setSearch, statusFilter, setStatusFilter, openApplication }: { applications: Application[]; filtered: Application[]; search: string; setSearch: (v: string) => void; statusFilter: string; setStatusFilter: (v: string) => void; openApplication: (id: string) => void }) {
  return <section className="panel applications-panel"><div className="toolbar"><label className="search-box"><Icon name="search" size={19}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Код, № CRM, клиент или объект"/><kbd>⌘ K</kbd></label><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} aria-label="Фильтр по статусу"><option>Все статусы</option>{statusOrder.map((status) => <option key={status}>{status}</option>)}</select><button className="button button--primary button--compact" onClick={() => setView("new-application")}><Icon name="plus" size={18}/>Новая заявка</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Код / № CRM</th><th>Клиент и объект</th><th>Сумма</th><th>Ответственный</th><th>Статус</th><th>Обновлено</th><th/></tr></thead><tbody>{filtered.map((app) => <tr key={app.id} onClick={() => openApplication(app.id)}><td><strong>{app.id}</strong><small>{app.crm}</small></td><td><strong>{app.client}</strong><small>{app.property}</small></td><td className="nowrap">{app.amount}</td><td>{app.owner}</td><td><StatusBadge status={app.status}/></td><td><small>{app.updated}</small></td><td><button className="icon-button" aria-label="Открыть заявку"><Icon name="chevron" size={18}/></button></td></tr>)}</tbody></table></div><div className="mobile-app-list">{filtered.map((app) => <button className="mobile-app-card" key={app.id} onClick={() => openApplication(app.id)}><div><span>{app.id}</span><StatusBadge status={app.status}/></div><strong>{app.client}</strong><small>{app.property}</small><footer><b>{app.amount}</b><span>{app.updated}</span></footer></button>)}</div><div className="table-footer"><span>Показано {filtered.length} из {applications.length}</span><div><button disabled>←</button><button className="active">1</button><button>2</button><button>→</button></div></div></section>;
}

function ApplicationDetail({ application, detailTab, setDetailTab, setView, role, docs, uploadDocument, notify, setModal }: { application: Application; detailTab: string; setDetailTab: (v: string) => void; setView: (v: View) => void; role: Role; docs: {name:string;size:string;author:string;source:string;date:string}[]; uploadDocument: (e: ChangeEvent<HTMLInputElement>) => void; notify: (m: string) => void; setModal: (v: string | null) => void }) {
  const tabs = [{id:"overview",label:"Обзор"},{id:"client",label:"Клиент"},{id:"decision",label:"Решение банка"},{id:"documents",label:"Документы",count:docs.length},{id:"history",label:"История"}];
  return <><button className="back-link page-back" onClick={() => setView("applications")}>← К списку заявок</button><section className="application-hero"><div><div className="application-code"><span>Код на сайте</span><strong>{application.id}</strong><button className="icon-button" onClick={() => notify("Код скопирован")}><Icon name="copy" size={17}/></button></div><h1>{application.client}</h1><p>{application.property}</p></div><div className="application-hero__side"><StatusBadge status={application.status}/><span>№ CRM <strong>{application.crm}</strong></span></div></section><div className="detail-tabs" role="tablist">{tabs.map((tab) => <button key={tab.id} className={detailTab === tab.id ? "active" : ""} onClick={() => setDetailTab(tab.id)}>{tab.label}{tab.count ? <em>{tab.count}</em> : null}</button>)}</div>
  {detailTab === "overview" && <div className="detail-grid"><section className="panel detail-main"><div className="panel__head"><div><span className="eyebrow">Ключевые параметры</span><h2>Ипотечная заявка</h2></div><button className="link-button" onClick={() => setDetailTab("client")}>Все данные</button></div><div className="detail-values"><div><span>Сумма кредита</span><strong>{application.amount}</strong></div><div><span>Стоимость объекта</span><strong>9 400 000 ₽</strong></div><div><span>Первоначальный взнос</span><strong>2 600 000 ₽</strong></div><div><span>Срок</span><strong>25 лет</strong></div><div><span>Программа</span><strong>Семейная ипотека</strong></div><div><span>Офис банка</span><strong>Ипотечный центр</strong></div></div><div className="consent-link-card"><div className="consent-link-card__icon"><Icon name="copy"/></div><div><strong>Ссылка для согласий клиента</strong><span>centrinvest.ru/consent/{application.id.toLowerCase()}</span><small>Действует до 21.08.2026 · клиент ещё не перешёл</small></div><div className="consent-link-card__actions"><button className="button button--secondary button--compact" onClick={() => notify("Ссылка скопирована")}><Icon name="copy" size={16}/>Скопировать</button><button className="link-button" onClick={() => setView("client-consent")}>Открыть путь клиента</button></div></div></section><aside className="detail-side"><section className="panel"><span className="eyebrow">Ответственный</span><div className="responsible"><span className="manager-photo">ЕК</span><div><strong>{application.owner}</strong><small>Менеджер по продажам</small></div></div>{role === "leader" && <button className="button button--secondary button--wide" onClick={() => setModal("reassign")}>Переназначить</button>}</section><section className="panel"><span className="eyebrow">Менеджер банка</span><div className="responsible"><span className="manager-photo manager-photo--bank">АЛ</span><div><strong>Андрей Лебедев</strong><small>Ипотечный центр</small></div></div><div className="manager-links"><a href="tel:+78632001212"><Icon name="phone" size={17}/>+7 863 200-12-12</a><a href="mailto:a.lebedev@centrinvest.ru"><Icon name="mail" size={17}/>a.lebedev@centrinvest.ru</a></div></section></aside></div>}
  {detailTab === "client" && <section className="panel detail-section"><div className="panel__head"><div><span className="eyebrow">Анкета</span><h2>Данные клиента</h2></div><button className="button button--secondary button--compact" onClick={() => notify("Редактирование доступно только в статусе «Черновик»")}>Редактировать</button></div><div className="info-groups">{[["Основные данные",[["ФИО",application.client],["Дата рождения","14.03.1992"],["Телефон",application.phone],["Email","a.orlova@example.ru"]]],["Паспорт и адрес",[["Паспорт","60 14 728461"],["Дата выдачи","18.04.2014"],["Код подразделения","610-004"],["Адрес регистрации","г. Ростов-на-Дону, ул. Текучёва, 18"]]],["Занятость и доход",[["Организация","АО «Южная логистика»"],["Должность","Руководитель отдела"],["Стаж","4 года 7 месяцев"],["Доход в месяц","168 000 ₽"]]]].map((group) => <div key={group[0] as string}><h3>{group[0] as string}</h3><dl>{(group[1] as string[][]).map((item) => <div key={item[0]}><dt>{item[0]}</dt><dd>{item[1]}</dd></div>)}</dl></div>)}</div></section>}
  {detailTab === "decision" && <section className="decision-card"><div className="decision-card__top"><div className="decision-check"><Icon name="check" size={28}/></div><div><span className="eyebrow">Предварительное решение</span><h2>Заявка предварительно одобрена</h2><p>Решение действительно до 28 августа 2026 года.</p></div></div><div className="decision-values"><div><span>Сумма</span><strong>6 800 000 ₽</strong></div><div><span>Ставка</span><strong>6,0%</strong></div><div><span>Срок</span><strong>25 лет</strong></div><div><span>Первоначальный взнос</span><strong>27,7%</strong></div></div><div className="decision-note"><strong>Общие условия</strong><p>Предоставление полного пакета документов и подтверждение стоимости объекта. Окончательные параметры будут указаны после проверки документов.</p></div><button className="button button--primary" onClick={() => notify("Решение скачано")}>Скачать решение</button></section>}
  {detailTab === "documents" && <section className="panel detail-section"><div className="panel__head"><div><span className="eyebrow">Файлы заявки</span><h2>Документы</h2><p>PDF, JPG, PNG, DOCX и XLSX · до 50 МБ</p></div><label className="button button--primary button--compact upload-button"><Icon name="upload" size={18}/>Добавить документ<input type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx" onChange={uploadDocument}/></label></div><div className="documents-list">{docs.map((doc,index) => <div className="document-row" key={`${doc.name}-${index}`}><span className={`file-icon file-icon--${doc.name.split(".").pop()?.toLowerCase()}`}>{doc.name.split(".").pop()?.slice(0,3)}</span><div className="document-row__main"><strong>{doc.name}</strong><small>{doc.size} · {doc.date}</small></div><span className={`source-pill ${doc.source === "Банк" ? "source-pill--bank" : ""}`}>{doc.source}</span><span className="document-author">{doc.author}</span><button className="icon-button" title="Скачать" onClick={() => notify(`Скачивание: ${doc.name}`)}><Icon name="download" size={18}/></button><button className="icon-button" title="Заменить" onClick={() => notify("Выберите новый файл для замены")}><Icon name="upload" size={18}/></button><button className="icon-button icon-button--danger" title="Удалить" onClick={() => setModal(`delete:${index}`)}><Icon name="close" size={18}/></button></div>)}</div></section>}
  {detailTab === "history" && <section className="panel detail-section"><div className="panel__head"><div><span className="eyebrow">Workflow</span><h2>История статусов</h2></div></div><div className="timeline">{[["Предварительно одобрена","14 августа 2026, 09:42","Решение получено из CRM банка"],["На проверке","14 августа 2026, 09:31","Заявка передана кредитному специалисту"],["Принята в работу","14 августа 2026, 09:30","Клиент предоставил все согласия"],["Ожидает согласия клиента","14 августа 2026, 09:18","Сформирована защищённая ссылка"],["Заявка отправлена","14 августа 2026, 09:17","Код на сайте CI-240814-0187"]].map((item,index) => <div className={`timeline-item ${index === 0 ? "timeline-item--current" : ""}`} key={item[0]}><span className="timeline-dot"><Icon name="check" size={13}/></span><div><strong>{item[0]}</strong><p>{item[2]}</p><time>{item[1]}</time></div></div>)}</div></section>}
  </>;
}

function NewApplication({ wizardStep, setWizardStep, notify, submitApplication }: { wizardStep: number; setWizardStep: React.Dispatch<React.SetStateAction<number>>; notify: (m: string) => void; submitApplication: () => void }) {
  const steps = ["Офис", "Клиент", "Паспорт", "Ипотека", "Объект", "Доходы", "Расходы", "Проверка"];
  const content = [
    <div className="wizard-form" key="office"><h2>Выберите офис банка</h2><p className="muted">Офис будет получать заявку и сопровождать сделку.</p><label className="office-option selected"><input type="radio" defaultChecked name="office"/><span className="radio-mark"/><div><strong>Ипотечный центр</strong><small>г. Ростов-на-Дону, пр. Соколова, 62</small></div><span>Рекомендуем</span></label><label className="office-option"><input type="radio" name="office"/><span className="radio-mark"/><div><strong>Дополнительный офис № 5</strong><small>г. Ростов-на-Дону, ул. Зорге, 56</small></div></label></div>,
    <div className="wizard-form" key="client"><h2>Основные данные клиента</h2><div className="form-grid"><Field label="Фамилия" value="Волкова"/><Field label="Имя" value="Софья"/><Field label="Отчество" value="Андреевна"/><Field label="Дата рождения" value="1991-09-22" type="date"/><Field label="Мобильный телефон" value="+7 928 440-18-62"/><Field label="Электронная почта" value="s.volkova@example.ru" type="email"/></div></div>,
    <div className="wizard-form" key="passport"><h2>Паспорт и адрес</h2><div className="form-grid"><Field label="Серия паспорта" value="60 16"/><Field label="Номер паспорта" value="491820"/><Field label="Дата выдачи" value="2016-10-12" type="date"/><Field label="Код подразделения" value="610-008"/><Field label="Кем выдан" value="ГУ МВД России по Ростовской области"/><Field label="Место рождения" value="г. Ростов-на-Дону"/><label className="field field--wide"><span>Адрес регистрации</span><input defaultValue="г. Ростов-на-Дону, ул. Пушкинская, д. 140, кв. 18"/></label></div><label className="check-row"><input type="checkbox" defaultChecked/><span className="custom-check"><Icon name="check" size={14}/></span>Адрес проживания совпадает с адресом регистрации</label></div>,
    <div className="wizard-form" key="mortgage"><h2>Параметры ипотеки</h2><div className="form-grid"><label className="field"><span>Ипотечная программа</span><select defaultValue="family"><option value="family">Семейная ипотека</option><option>Ипотека новостройки</option><option>IT-ипотека</option><option>Зелёная ипотека</option></select></label><Field label="Стоимость объекта" value="9 800 000 ₽"/><Field label="Первоначальный взнос" value="2 350 000 ₽"/><Field label="Сумма кредита" value="7 450 000 ₽"/><Field label="Срок кредита" value="25 лет"/><label className="field"><span>Цель кредита</span><select><option>Приобретение квартиры</option><option>Рефинансирование</option></select></label></div><div className="calculation-note"><strong>Предварительный расчёт</strong><span>Платёж от 47 996 ₽ / месяц</span><small>Расчёт информационный и не является решением банка.</small></div></div>,
    <div className="wizard-form" key="property"><h2>Информация об объекте</h2><div className="form-grid"><Field label="Застройщик" value="ООО СЗ «Грин Парк»"/><Field label="Жилой комплекс" value="ЖК «Грин Парк»"/><Field label="Адрес объекта" value="г. Ростов-на-Дону, ул. Нансена, 111"/><Field label="Номер квартиры" value="214"/><Field label="Площадь" value="63,8 м²"/><Field label="Срок сдачи" value="IV квартал 2027"/></div></div>,
    <div className="wizard-form" key="income"><h2>Занятость и доходы</h2><div className="form-grid"><Field label="Организация" value="АО «Донские технологии»"/><Field label="ИНН организации" value="6163014820"/><Field label="Должность" value="Ведущий аналитик"/><Field label="Стаж на текущем месте" value="3 года 2 месяца"/><Field label="Ежемесячный доход" value="154 000 ₽"/><label className="field"><span>Подтверждение дохода</span><select><option>Справка работодателя</option><option>Выписка СФР</option></select></label></div></div>,
    <div className="wizard-form" key="expenses"><h2>Расходы и обязательства</h2><div className="form-grid"><Field label="Ежемесячные расходы" value="48 000 ₽"/><Field label="Платежи по кредитам" value="12 500 ₽"/><Field label="Количество иждивенцев" value="1"/><label className="field"><span>Дополнительное обеспечение</span><select><option>Не требуется</option><option>Поручительство</option></select></label></div><label className="check-row"><input type="checkbox" defaultChecked/><span className="custom-check"><Icon name="check" size={14}/></span>Других обязательств нет</label></div>,
    <div className="wizard-review" key="review"><div className="review-success"><Icon name="check" size={24}/><div><strong>Все обязательные поля заполнены</strong><span>Проверьте данные перед отправкой заявки.</span></div></div><div className="review-sections">{[["Клиент","Софья Андреевна Волкова","+7 928 440-18-62"],["Ипотека","Семейная ипотека","7 450 000 ₽ · 25 лет"],["Объект","ЖК «Грин Парк», кв. 214","Стоимость 9 800 000 ₽"],["Доход","АО «Донские технологии»","154 000 ₽ в месяц"]].map((item,index) => <button key={item[0]} onClick={() => setWizardStep(index === 0 ? 1 : index === 1 ? 3 : index === 2 ? 4 : 5)}><div><span>{item[0]}</span><strong>{item[1]}</strong><small>{item[2]}</small></div><Icon name="chevron" size={18}/></button>)}</div><div className="submission-note"><strong>После отправки</strong><p>ЛКП присвоит код на сайте, передаст заявку в CRM и сформирует ссылку для согласий клиента.</p></div></div>,
  ];
  return <div className="wizard-layout"><aside className="wizard-nav"><div className="wizard-progress-mobile"><span>Шаг {wizardStep + 1} из {steps.length}</span><strong>{steps[wizardStep]}</strong><i><em style={{width:`${((wizardStep + 1) / steps.length) * 100}%`}}/></i></div>{steps.map((step,index) => <button key={step} className={`${wizardStep === index ? "active" : ""} ${wizardStep > index ? "done" : ""}`} onClick={() => index <= wizardStep && setWizardStep(index)}><span>{wizardStep > index ? <Icon name="check" size={14}/> : index + 1}</span><div><small>Шаг {index + 1}</small><strong>{step}</strong></div></button>)}</aside><section className="panel wizard-panel">{content[wizardStep]}<footer className="wizard-actions"><button className="button button--secondary" disabled={wizardStep === 0} onClick={() => setWizardStep((step) => Math.max(0, step - 1))}>Назад</button><button className="link-button" onClick={() => notify("Черновик сохранён")}>Сохранить черновик</button>{wizardStep < steps.length - 1 ? <button className="button button--primary" onClick={() => setWizardStep((step) => Math.min(steps.length - 1, step + 1))}>Продолжить <span>→</span></button> : <button className="button button--primary" onClick={submitApplication}>Отправить заявку</button>}</footer></section></div>;
}

function Employees({ setModal }: { setModal: (v: string) => void }) { return <section className="panel applications-panel"><div className="toolbar toolbar--simple"><div><span className="eyebrow">ООО СЗ «Грин Парк»</span><h2>Команда партнёра</h2></div><button className="button button--primary button--compact" onClick={() => setModal("invite")}><Icon name="plus" size={18}/>Добавить сотрудника</button></div><div className="employee-list">{[["Елена Кравцова","Менеджер по продажам","e.kravtsova@greenpark.ru","18 заявок","Активен"],["Илья Романов","Менеджер по продажам","i.romanov@greenpark.ru","12 заявок","Активен"],["Марина Соколова","Руководитель отдела","m.sokolova@greenpark.ru","30 заявок","Активен"],["Антон Ларин","Менеджер по продажам","a.larin@greenpark.ru","0 заявок","Приглашён"]].map((item) => <div className="employee-row" key={item[0]}><span className="client-avatar">{item[0].split(" ").map((w) => w[0]).join("")}</span><div><strong>{item[0]}</strong><small>{item[1]}</small></div><span>{item[2]}</span><span>{item[3]}</span><span className={`user-state ${item[4] === "Приглашён" ? "user-state--pending" : ""}`}>{item[4]}</span><button className="icon-button"><Icon name="more"/></button></div>)}</div></section>; }
function Partners({ setModal }: { setModal: (v: string) => void }) { return <section className="panel applications-panel"><div className="toolbar"><label className="search-box"><Icon name="search"/><input placeholder="Название или ИНН партнёра"/></label><select><option>Все типы</option><option>Застройщик</option><option>Агентство недвижимости</option></select><button className="button button--primary button--compact" onClick={() => setModal("partner")}><Icon name="plus" size={18}/>Добавить партнёра</button></div><div className="partners-grid">{[["ООО СЗ «Грин Парк»","6166114280","Застройщик","18 пользователей","46 заявок"],["ООО СЗ «Северный Берег»","6165221041","Застройщик","9 пользователей","28 заявок"],["АО «РостовДомСтрой»","6163098124","Застройщик","14 пользователей","35 заявок"],["АН «Мой город»","6165112819","Агентство недвижимости","6 пользователей","12 заявок"]].map((item) => <button className="partner-card" key={item[0]}><div className="partner-mark"><Icon name="building"/></div><div><strong>{item[0]}</strong><small>ИНН {item[1]}</small></div><span>{item[2]}</span><footer><small>{item[3]}</small><small>{item[4]}</small></footer></button>)}</div></section>; }
function Users({ setModal, notify }: { setModal: (v: string) => void; notify: (m: string) => void }) { return <section className="panel applications-panel"><div className="toolbar"><label className="search-box"><Icon name="search"/><input placeholder="ФИО, email или партнёр"/></label><select><option>Все роли</option><option>Сотрудник</option><option>Руководитель</option></select><button className="button button--primary button--compact" onClick={() => setModal("invite")}><Icon name="plus" size={18}/>Создать пользователя</button></div><div className="employee-list">{[["Елена Кравцова","ООО СЗ «Грин Парк»","Сотрудник","Активен"],["Марина Соколова","ООО СЗ «Грин Парк»","Руководитель","Активен"],["Илья Романов","ООО СЗ «Грин Парк»","Сотрудник","Заблокирован"],["Олег Карпов","АО «РостовДомСтрой»","Руководитель","Активен"]].map((item) => <div className="employee-row employee-row--admin" key={item[0]}><span className="client-avatar">{item[0].split(" ").map((w) => w[0]).join("")}</span><div><strong>{item[0]}</strong><small>{item[1]}</small></div><span>{item[2]}</span><span className={`user-state ${item[3] === "Заблокирован" ? "user-state--blocked" : ""}`}>{item[3]}</span><button className="button button--secondary button--tiny" onClick={() => notify(item[3] === "Заблокирован" ? "Пользователь разблокирован" : "Пароль сброшен")}>{item[3] === "Заблокирован" ? "Разблокировать" : "Сбросить пароль"}</button><button className="icon-button"><Icon name="more"/></button></div>)}</div></section>; }
function Marketing({ notify }: { notify: (m: string) => void }) { return <div className="marketing-layout"><section className="panel marketing-editor"><span className="eyebrow">Демонстрация контента</span><h2>Баннер для застройщиков</h2><Field label="Заголовок" value="Семейная ипотека"/><label className="field"><span>Описание</span><textarea defaultValue="Помогите клиентам выбрать квартиру с программой господдержки."/></label><div className="form-grid"><Field label="Текст кнопки" value="Материалы для продаж"/><Field label="Ссылка" value="/mortgage/family"/></div><label className="field"><span>Сегмент</span><select><option>Застройщики</option><option>Все партнёры</option></select></label><label className="check-row"><input type="checkbox" defaultChecked/><span className="custom-check"><Icon name="check" size={14}/></span>Баннер активен</label><button className="button button--primary" onClick={() => notify("Настройки баннера сохранены")}>Сохранить</button></section><aside><span className="eyebrow">Предпросмотр</span><div className="promo-card promo-card--preview"><span className="promo-card__tag">Для партнёров</span><h2>Семейная ипотека</h2><p>Помогите клиентам выбрать квартиру с программой господдержки.</p><button>Материалы для продаж <Icon name="chevron" size={16}/></button><div className="promo-shape"/></div><small className="preview-caption">Так баннер отображается на главной странице партнёра.</small></aside></div>; }

function Modal({ modal, setModal, setDocs, notify }: { modal: string | null; setModal: (v: string | null) => void; setDocs: React.Dispatch<React.SetStateAction<{name:string;size:string;author:string;source:string;date:string}[]>>; notify: (m: string) => void }) {
  if (!modal) return null;
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal-card"><button className="modal-close" onClick={() => setModal(null)}><Icon name="close"/></button>{modal.startsWith("delete:") ? <><span className="modal-icon modal-icon--danger"><Icon name="close"/></span><h2>Удалить документ?</h2><p>Документ будет удалён из заявки. Это действие отображается в журнале операций.</p><div className="modal-actions"><button className="button button--secondary" onClick={() => setModal(null)}>Отмена</button><button className="button button--danger" onClick={() => { const index = Number(modal.split(":")[1]); setDocs((items) => items.filter((_, i) => i !== index)); setModal(null); notify("Документ удалён"); }}>Удалить</button></div></> : modal === "reassign" ? <><span className="eyebrow">Ответственный сотрудник</span><h2>Переназначить заявку</h2><label className="field"><span>Новый ответственный</span><select><option>Илья Романов</option><option>Елена Кравцова</option><option>Марина Соколова</option></select></label><div className="modal-actions"><button className="button button--secondary" onClick={() => setModal(null)}>Отмена</button><button className="button button--primary" onClick={() => { setModal(null); notify("Ответственный изменён"); }}>Переназначить</button></div></> : <><span className="eyebrow">{modal === "partner" ? "Новая организация" : "Новый пользователь"}</span><h2>{modal === "partner" ? "Добавить партнёра" : "Создать учётную запись"}</h2>{modal === "partner" ? <><Field label="Название организации" placeholder="ООО СЗ «Название»"/><div className="form-grid"><Field label="ИНН" placeholder="10 цифр"/><label className="field"><span>Тип партнёра</span><select><option>Застройщик</option><option>Агентство недвижимости</option></select></label></div></> : <><Field label="ФИО" placeholder="Фамилия Имя Отчество"/><Field label="Электронная почта" placeholder="user@company.ru" type="email"/><label className="field"><span>Роль</span><select><option>Сотрудник</option><option>Руководитель</option></select></label></>}<div className="modal-actions"><button className="button button--secondary" onClick={() => setModal(null)}>Отмена</button><button className="button button--primary" onClick={() => { setModal(null); notify(modal === "partner" ? "Партнёр добавлен" : "Приглашение отправлено"); }}>Создать</button></div></>}</div></div>;
}
